# Generated by Django 6.0.1 on 2026-02-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Centro', max_length=50),
        ),
        migrations.AddField(
            model_name='visita',
            name='latitude_checkin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='longitude_checkin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
