# Generated by Django 6.0.1 on 2026-02-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_carteira_cliente_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='concorrente_empresa',
            field=models.CharField(blank=True, help_text='Cor do botijão ou marca', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='concorrente_preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='data_agendamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='motivo_nao_venda',
            field=models.CharField(blank=True, choices=[('NAO_PRECISA', 'Não precisa de gás no momento'), ('CONCORRENCIA', 'Comprou da Concorrência'), ('OUTROS', 'Outros / Ausente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADA', 'Venda Realizada'), ('NAO_VENDA', 'Não Comprou / Outros')], default='PENDENTE', max_length=20),
        ),
    ]
