# Generated by Django 6.0.1 on 2026-02-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_visita_concorrente_empresa_visita_concorrente_preco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carteira',
        ),
        migrations.AddField(
            model_name='cliente',
            name='carteiras',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='logistica.carteira'),
        ),
        migrations.AlterField(
            model_name='visita',
            name='concorrente_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
