# Generated by Django 6.0.1 on 2026-02-19 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_remove_cliente_carteira_cliente_carteiras_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira',
            name='agente_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras_comerciais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('VENDA_FECHADA', 'Venda Fechada (Gerar Entrega)'), ('RECUSA', 'Não Quis / Concorrência / Acha Caro'), ('CAIXA_POSTAL', 'Caixa Postal / Não Atende / Número Errado'), ('REAGENDADO', 'Pediu para ligar mais tarde')], max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_ligacao', models.DateTimeField(auto_now_add=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ligacoes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_ligacoes', to='logistica.cliente')),
            ],
        ),
    ]
