# Generated by Django 6.0.1 on 2026-02-26 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0006_carteira_agente_comercial_ligacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='data_agendamento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciclo_consumo_dias',
            field=models.IntegerField(default=30, help_text='Média de dias que o gás dura neste cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='data_ultima_venda',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ligacao',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='agente_comercial',
            field=models.ForeignKey(blank=True, help_text='Responsável pelas ligações', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras_venda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='cor_etiqueta',
            field=models.CharField(default='#F26522', help_text='Código HEX da cor', max_length=7),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='motoqueiro',
            field=models.ForeignKey(blank=True, help_text='Responsável pela entrega física', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras_moto', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Centro', max_length=100),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='agente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.cliente'),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='resultado',
            field=models.CharField(choices=[('VENDA_FECHADA', 'Venda Fechada'), ('RECUSA', 'Recusa'), ('CAIXA_POSTAL', 'Caixa Postal'), ('REAGENDADO', 'Ligar Depois')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='concorrente_preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='motivo_nao_venda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADA', 'Venda Realizada'), ('NAO_VENDA', 'Não Vendeu')], default='PENDENTE', max_length=20),
        ),
    ]
