# Generated by Django 6.0.1 on 2026-03-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_remove_visita_data_agendamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='carteiras',
        ),
        migrations.AddField(
            model_name='carteira',
            name='clientes',
            field=models.ManyToManyField(blank=True, related_name='carteiras', to='logistica.cliente'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='agente_comercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras_comerciais', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='cor_etiqueta',
            field=models.CharField(default='#F26522', max_length=7),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='motoqueiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carteiras_logistica', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default='Não Informado', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciclo_consumo_dias',
            field=models.IntegerField(default=30, help_text='Média de dias entre as compras'),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='data_retorno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ligacao',
            name='resultado',
            field=models.CharField(choices=[('VENDA_FECHADA', 'Venda Fechada'), ('RECUSA', 'Recusa / Concorrência'), ('CAIXA_POSTAL', 'Sem Atender / Caixa Postal'), ('REAGENDADO', 'Retornar Depois')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visita',
            name='concorrente_preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='visita',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('REALIZADA', 'Realizada'), ('NAO_VENDA', 'Não Venda / Recusa')], default='PENDENTE', max_length=20),
        ),
    ]
