# Generated by Django 6.0.1 on 2026-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_remove_cliente_carteiras_carteira_clientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='tipo_botijao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visita',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
