# Generated by Django 6.0.1 on 2026-03-06 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0009_visita_forma_pagamento_visita_tipo_botijao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, help_text='CPF ou CNPJ', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observacoes_gerais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
