# Generated by Django 6.0.1 on 2026-03-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0010_cliente_documento_cliente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligacao',
            name='concorrente_empresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ligacao',
            name='concorrente_preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ligacao',
            name='motivo_nao_venda',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
